kinit.c needs to include new resume.h
fix:   KLIBCCC usr/kinit/kinit.o
usr/kinit/kinit.c: In function 'main':
usr/kinit/kinit.c:280: warning: implicit declaration of function
'do_resume'