[klibc] include: [sys/types.h] -> linux/types.h and __aligned_u64
When building klibc 1.5.25 against linux/master (ie. post 3.1) I'm seeing:

klibc/generated/include/linux/if_packet.h:176: error: expected
specifier-qualifier-list before '__aligned_u64'

which seems to come from upstream commits:
0d4691ce112be025019999df5f2a5e00c03f03c2 remotes/linux/master~90^2~408  (origin)
96c131842aab45b5d139d0bcb417796819f5ee92 remotes/linux/master~90^2~169
 (change from aligned_u64 to __aligned_u64)

and collides with klibc/usr/include/sys/types.h

/* Keeps linux/types.h from getting included elsewhere */
#define _LINUX_TYPES_H

not defining __aligned_u64 like the kernel's include/linux/types.h does.

Signed-off-by: maximilian attems <max@stro.at>