mips: fix compilation against linux-libc-dev
contrary to linux-kernel-headers those headers are no longer available:
In file included from usr/klibc/arch/mips/crt0.S:11:
usr/include/arch/mips/machine/asm.h:8:24: error: asm/regdef.h: No such file
usr/include/arch/mips/machine/asm.h:9:21: error: asm/asm.h: No such file or

replicate the headers inside klibc.

Signed-off-by: maximilian attems <max@stro.at>