[klibc] include: [mntent.h] Add MNTTYPE_SWAP definition
It is used by util-linux mount code:
mount.c:1004:30: error: ‘MNTTYPE_SWAP’ undeclared (first use in this function)
..

Signed-off-by: maximilian attems <max@stro.at>